### ISSUE TITLE
Ion Icons

### ISSUE THREAD

**Issue by AFink** [MexsonFernandes/nuxt-ionic-capacitor-app#2]
Hi, the way you implemented the ions doesn't work for me.... Also I looked at your site, there isnt it working, too....
Do you have an idea how to fix that?

**Comment by MexsonFernandes** [comment]
@AFink thanks for reporting it out. I will check the code.

**Comment by MexsonFernandes** [comment]
I have updated the code now it supports ion icons.

![image](https://user-images.githubusercontent.com/22270770/119980793-6698d580-bfda-11eb-8c36-6461f3c5ea55.png)
