### ISSUE TITLE
ion-input etc not taking v-model

### ISSUE THREAD

**Issue by xewl** [MexsonFernandes/nuxt-ionic-capacitor-app#3]
Seems like the Vue support for Ionic wasn't pulled in?

```
<ion-input
  v-model="password"
  type="password"
  placeholder="••••••••••"
  required
></ion-input>
```

Won't update "password" in data.

I can see that there's the ionic.js plugin, but :S

**Comment by MexsonFernandes** [comment]
Thanks for the input @xewl. The support shouldn't be external as Vue is the base and Ionic is integrated. Let me reproduce your error on my end.

**Comment by xewl** [comment]
Vue has it's own support layer in ionic/vue to give v-model support to these components
But while trying to import from that I've hit some issues with ionic/vue-router giving warnings and the app not working.
I've also forwarded this as a question to compadré @daggerok at daggerok/ionic-nuxt-app#5

You two seem to have the most experience with this setup (Nuxt, Vue, Ionic).

**Comment by MexsonFernandes** [comment]
@xewl for now I have added an alternate fix which will handle v-model. I am waiting for Nuxt 3 beta to be rolled out so that [@ionic/vue](https://www.npmjs.com/package/@ionic/vue) package can be utilized to experiment more with Nuxt + Ionic setup.

**Comment by xewl** [comment]
Thanks for looking into it!
