### ISSUE TITLE
error while installing on vercel nextjs

### ISSUE THREAD

**Issue by imranaalam** [MexsonFernandes/nuxt-ionic-capacitor-app#5]
23:45:06.502
warning "nuxt > @nuxt/components@2.1.8" has unmet peer dependency "consola@*".
23:45:06.509
warning "@nuxtjs/eslint-config > eslint-plugin-jest > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
23:45:06.509
warning "@nuxtjs/eslint-module > eslint-webpack-plugin@2.5.4" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
23:45:06.509
warning "eslint-plugin-nuxt > eslint-plugin-vue@6.2.2" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
23:45:20.281
[4/4] Building fresh packages...
23:45:21.384
Done in 32.87s.
23:45:21.598
Running "yarn run build"
23:45:21.775
yarn run v1.22.10
23:45:21.802
$ nuxt build
23:45:45.126
Done in 23.35s.
23:45:45.143
Error: No Output Directory named "dist" found after the Build completed. You can configure the Output Directory in your Project Settings. Learn More: https://vercel.link/missing-public-directory

**Comment by imranaalam** [comment]
sorry, i dont know how to built in vercel pipeline.

**Comment by MexsonFernandes** [comment]
@imranaalam in Vercel deployment settings, we need following configurations:
![image](https://user-images.githubusercontent.com/22270770/133275191-f2b94474-02dd-4259-9cab-24ef27f6bcda.png)

**Comment by MexsonFernandes** [comment]
tested with latest main push with the vercel button and it works fine. Reopen @imranaalam if issue persist.
