### ISSUE TITLE
Immediately crashes when deploying to android

### ISSUE THREAD

**Issue by thepure12** [MexsonFernandes/nuxt-ionic-capacitor-app#9]

**Comment by avinmaster** [comment]
Solved?

**Comment by PMLS3** [comment]
Same error

**Comment by MexsonFernandes** [comment]
can anyone post the logs from the terminal ?

**Comment by MexsonFernandes** [comment]
I could reproduce the error on my side. Let me push a fix for this.

**Comment by PMLS3** [comment]
> can anyone post the logs from the terminal ?
![phone](https://user-images.githubusercontent.com/62140524/149186044-dfd23ebe-b4de-4675-9336-c8639f828296.PNG)
![Capture](https://user-images.githubusercontent.com/62140524/149186057-32fec577-ad98-4b0a-8ed5-d866c512c4f4.PNG)

**Comment by MexsonFernandes** [comment]
I have pushed some fixes in #33.

Use `yarn cap:android` to start the app. It will also open Android Studio if configured in env variables. Otherwise open Android Studio manually after this command.

If issue persists, feel free to reopen. Happy to help.

**Comment by darren-trottier** [comment]
It seem that error still persist : 

![image](https://user-images.githubusercontent.com/57952871/186424899-c9e23d33-3381-43db-8a1d-4c7de9906707.png)
